import { Hotel } from './types';

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'h1',
    name: 'Grand Hyatt San Francisco',
    description: 'A luxurious hotel located in the heart of Union Square, offering breathtaking city views and exceptional service.',
    imageUrl: 'https://picsum.photos/600/400?random=1',
    pricePerNight: 350,
    rating: 4.7,
    address: '345 Stockton St, San Francisco, CA 94108',
  },
  {
    id: 'h2',
    name: 'The St. Regis Aspen Resort',
    description: 'An exquisite resort nestled at the base of Aspen Mountain, known for its elegant rooms and world-class spa.',
    imageUrl: 'https://picsum.photos/600/400?random=2',
    pricePerNight: 800,
    rating: 4.9,
    address: '315 E Dean St, Aspen, CO 81611',
  },
  {
    id: 'h3',
    name: 'Waldorf Astoria Orlando',
    description: 'A serene luxury hotel surrounded by Bonnet Creek Nature Preserve, offering a championship golf course and a relaxing spa.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
    pricePerNight: 450,
    rating: 4.6,
    address: '14200 Bonnet Creek Resort Ln, Orlando, FL 32821',
  },
  {
    id: 'h4',
    name: 'The Ritz-Carlton, Laguna Niguel',
    description: 'Perched atop a 150-foot bluff, this iconic resort offers panoramic ocean views, direct beach access, and refined coastal luxury.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
    pricePerNight: 700,
    rating: 4.8,
    address: '1 Ritz Carlton Dr, Dana Point, CA 92629',
  },
  {
    id: 'h5',
    name: 'Four Seasons Resort Maui at Wailea',
    description: 'An oceanfront paradise featuring spacious rooms, three stunning pools, and unparalleled service in a vibrant tropical setting.',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    pricePerNight: 1200,
    rating: 4.9,
    address: '3900 Wailea Alanui Dr, Kihei, HI 96753',
  },
  {
    id: 'h6',
    name: 'The Peninsula Chicago',
    description: 'A distinguished hotel on Magnificent Mile, combining classic elegance with modern amenities and spectacular city views.',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    pricePerNight: 600,
    rating: 4.7,
    address: '108 E Superior St, Chicago, IL 60611',
  },
  {
    id: 'h7',
    name: 'Mandarin Oriental, New York',
    description: 'Located high above Columbus Circle, offering luxurious accommodations, world-class dining, and breathtaking views of Central Park and the Manhattan skyline.',
    imageUrl: 'https://picsum.photos/600/400?random=7',
    pricePerNight: 950,
    rating: 4.8,
    address: '80 Columbus Cir, New York, NY 10023',
  },
  {
    id: 'h8',
    name: 'The Beverly Hills Hotel',
    description: 'The iconic "Pink Palace" on Sunset Boulevard, famous for its glamorous history, lush gardens, and legendary bungalows.',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    pricePerNight: 1100,
    rating: 4.7,
    address: '9641 Sunset Blvd, Beverly Hills, CA 90210',
  },
  {
    id: 'h9',
    name: 'Bellagio Las Vegas',
    description: 'A luxurious resort and casino renowned for its spectacular fountains, fine dining, and impressive art collection, located on the Las Vegas Strip.',
    imageUrl: 'https://picsum.photos/600/400?random=9',
    pricePerNight: 280,
    rating: 4.5,
    address: '3600 S Las Vegas Blvd, Las Vegas, NV 89109',
  },
  {
    id: 'h10',
    name: 'The Jefferson, Washington, DC',
    description: 'A historic boutique hotel known for its intimate atmosphere, personalized service, and proximity to the White House and other national landmarks.',
    imageUrl: 'https://picsum.photos/600/400?random=10',
    pricePerNight: 550,
    rating: 4.9,
    address: '1200 16th St NW, Washington, DC 20036',
  },
];